### ISSUE TITLE
DeckFactoryTest.checkIncludeSpecifiedCardsUnlimitedCopies() sometimes fails the second assertion

### ISSUE THREAD

**Issue by slaymaker1907** [oyachai/HearthSim#117]
For some reason, this test method has been failing on the second assertion (and seemingly only on the second assertion) 1 out of every couple hundred runs.

**Comment by slaymaker1907** [comment]
The error also exists for DeckFactoryTest.checkIncludeSpecifiedCardsLimitedCopies().

**Comment by slaymaker1907** [comment]
Bug was in the test since it didn't account for the fact that the included cards could be the same card.

**Comment by oyachai** [comment]
Thanks for looking into it.
