### ISSUE TITLE
Missing weapons (pre-GvG)

### ISSUE THREAD

**Issue by MrHen** [oyachai/HearthSim#53]
These were pulled out of the `all collectible cards implemented` test. I ignored all GvG cards and Eaglehorn Bow since it depends on Secrets which are not implemented yet (see #34). The four weapons below should be relatively straightforward to implement.

I can certainly do this but I didn't want to overlap with whatever you were working on.

<pre>
23:01:12.333 [main] WARN  c.h.test.json.ReferenceCardSpec - com.hearthsim.json.registry.ReferenceCard(DS1_188, Gladiator's Longbow, Weapon, Classic, Epic, 7, Hunter, Your hero is <b>Immune</b> while attacking., null, 5, null, 2, true)
23:01:12.334 [main] WARN  c.h.test.json.ReferenceCardSpec - com.hearthsim.json.registry.ReferenceCard(EX1_411, Gorehowl, Weapon, Classic, Epic, 7, Warrior, Attacking a minion costs 1 Attack instead of 1 Durability., null, 7, null, 1, true)
23:01:12.334 [main] WARN  c.h.test.json.ReferenceCardSpec - com.hearthsim.json.registry.ReferenceCard(EX1_133, Perdition's Blade, Weapon, Classic, Rare, 3, Rogue, <b>Battlecry:</b> Deal 1 damage. <b>Combo:</b> Deal 2 instead., [Battlecry, Combo], 2, null, 2, true)
23:01:12.335 [main] WARN  c.h.test.json.ReferenceCardSpec - com.hearthsim.json.registry.ReferenceCard(FP1_021, Death's Bite, Weapon, Curse of Naxxramas, Common, 4, Warrior, <b>Deathrattle:</b> Deal 1 damage to all minions., [Deathrattle], 4, null, 2, true)
</pre>

**Comment by MrHen** [comment]
I started work on this.

**Comment by oyachai** [comment]
got it, thanks
