### ISSUE TITLE
Adjacent auras (2 cards)

### ISSUE THREAD

**Issue by MrHen** [oyachai/HearthSim#58]
Looking through the list of unimplemented cards shows two cards with adjacent auras

```
ReferenceCard(EX1_565, Flametongue Totem, Minion, Basic, Common, 2, Shaman, Adjacent minions have +2 Attack., [AdjacentBuff, Aura], 0, 3, null, true)
ReferenceCard(EX1_162, Dire Wolf Alpha, Minion, Classic, Common, 2, Neutral, Adjacent minions have +1 Attack., [AdjacentBuff, Aura], 2, 2, null, true)
```

**Comment by MrHen** [comment]
Also, Wee Spellstopper has a similar mechanic but instead of stat bonuses it gives targeting immunity. So... something to think about while implementing this.

**Comment by MrHen** [comment]
Starting on this.

**Comment by oyachai** [comment]
How do you plan to implement this?  Adjacent aura checks for every minion placement and removal?

**Comment by MrHen** [comment]
I have a couple ideas to try out but the first attempt will be having these implement MinionPlacedInterface and check for adjacency.

**Comment by MrHen** [comment]
I'm no longer looking at this; got totally sidetracked by Heroes of the Storm. I wouldn't expect any PRs from me in the near future, sorry.

(On the other hand, if you play HotS, I'm always looking for more friends to play with...)
