### ISSUE TITLE
Battlecry refactoring in progress

### ISSUE THREAD

**Issue by MrHen** [oyachai/HearthSim#83]
This weekend I had way too much extra time and dug deep into the battlecry code looking to find a more common solution for targeting and tracking actions. I found one but it ended up impacting every card with a targetable battlecry and has fairly drastic implications on how we handle things.

I'll try to get a PR out in the next few days but hopefully you aren't in the middle of any major refactoring. If so, I'll try to handle the merging so you don't have to.

**Comment by oyachai** [comment]
One thing that I did was to move the Battlecry interfaces out of Minion and into Card class, mostly to implement Perdition's Blade.  I haven't pushed it yet, so I can hold off until you are done if that makes things easier.

**Comment by MrHen** [comment]
I ran into an issue so I wouldn't wait for me. I'll deal with merging it all together later.
