### ISSUE TITLE
File reorganization

### ISSUE THREAD

**Issue by MrHen** [oyachai/HearthSim#90]
How do you feel about reorganizing how the card files are laid out? If we group things by:

* Set
* Rarity

Then our subfolders won't continue to grow and grow as we implement new cards. It's already getting to be somewhat of a pain to deal with all of the Minion cards living in the same folder.

**Comment by oyachai** [comment]
Yep, I agree.

Do you have any particular preference for ordering?
* cardtype.set.rarity.CardName
* set.cardtype.rarity.CardName
* other permutations

If there are no preferences, I would go with set.cardtype.rarity.CardName.

**Comment by MrHen** [comment]
I think set.cardtype.rarity.CardName works.

**Comment by oyachai** [comment]
Will push in the next couple of days.

**Comment by MrHen** [comment]
Alright; I'll hold off on any refactoring then. :)

**Comment by oyachai** [comment]
done!

**Comment by oyachai** [comment]
reminder to myself: GUI is probably broken due to this change.

**Comment by MrHen** [comment]
Yeah, looks like the CardFactory isn't working anymore. Created https://github.com/oyachai/HearthSim/issues/104 to track the problem.
